### PR TITLE
docs: add visual display of affordances

### PR DESCRIPTION
**Pull request by benkoshy**
###    What is this PR?
    
* Add images of all the front end helpers pagy offers, in the readme.
    
###    Why?    
* To make it easier for users to see what is available in pagy, i.e. to make discovery of "affordances" easier.
* I view issue 307 as a symptom of a discovery problem: https://github.com/ddnexus/pagy/issues/307
    
This PR seeks to remedy it.
    
###    Problems with PR:
    
* we are using retype components in the markdown, and this will not display correctly in Github. We essentially need two Readmes if this proposal is acceptable.

### CODE REVIEW

**Comment by ddnexus** [comment]
The info displayed in the pict looks quite limited.

**Comment by benkoshy** [comment]
@ddnexus 

See below for screen shot. Shows all the view helpers.
image

**Comment by ddnexus** [comment]
This is what I see in the Files tab:

IMG_20230303_085555

**Comment by benkoshy** [comment]
> This is what I see in the Files tab:

I'm using some existing images which are already contained in the pagy repo - hence there is only 1 image in the files tab.

**Comment by ddnexus** [comment]
My concern is that it looks like a payy_info with partial info, but I don't have my laptop to run retype...

**Comment by ddnexus** [comment]
Indeed. Showing the page 1 for `page_info` is a very special case. I think using the output for multiple pages would give a more complete idea.

**Comment by benkoshy** [comment]
> Indeed. Showing the page 1 for `page_info` is a very special case. I think using the output for multiple pages would give a more complete idea.

I can change display no prob.

**Comment by ddnexus** [comment]
We cannot put this in the readme, but move its content somewhere appropriate in the docs.

In the readme:

1. It is kind of hidden while it should deserve its own prominent place
2. The readme must be readable by Github which does not understrand tabs

**Comment by benkoshy** [comment]
> We cannot put this in the readme, but move its content somewhere appropriate in the docs.

Exactly: the proposed changes to the readme will not work with github markdown, but will work with retype.


> In the readme:
> 
>     It is kind of hidden while it should deserve its own prominent place
>     It must be readable by Github which does not understrand tabs
> 

This is one way of solving the problem. I would bring to consideration another way - and would invite your thoughts?

**Option 1: Fork the two:**

we'd have to "fork" the two somehow, but then we'd have two copies that need to be maintained. 

**Option 2:  Streamline github and link to retype:**

What about streamlining the existing readme, to keep the graphs / benefits, but to move the actual docs into the retype site.  

See [view components which  does this well](https://github.com/ViewComponent/view_component). I had alluded to this before - but this time the difference now is we have an immediate / potential use case:

restructure

### What do you think?

**Comment by ddnexus** [comment]
I would avoid different readme. 
We could also consider a "showcase" page with the screenshots of all the styles and helpers in a table layout.

It could be added as a specific doc page linked in the readme, or right in the readme.

**Comment by benkoshy** [comment]
How about something like this?

pagy_view_helpers

pros / cons?

- pro: it's super easy.
- con: takes up too much space.

**Comment by ddnexus** [comment]
My simplest idea would be a table of 2 columns description and pict, without headers, just the content, so one line per item of the showcase.

The description should indicate the generic helper names and there should be a note with the info "bootstrap style displayed" somewhere.

As a more complete alternative the showcase could have 3 columns (with headers helper style, nav/nav_js, combo) and shows the pict for each CSS frameworks. An extra row/line for the other helpers like items, info.

**Comment by benkoshy** [comment]
Closing in favour of PR on ddnexus/pagy.

**Pull request closed without merging**
