### PR TITLE
Sample of restructuring JS docs

### PR DESCRIPTION
**Pull request by benkoshy**
@ddnexus 

Further to #3.

### What I did? Summary:

* Added affordances with images at the top.
* Aggressively removed extraneous words, for simplicity.
* Remove duplicated content
* Merged large parts of the javascripts readme.
* Use tabs / drop downs / panels and other retype components where applicable. I wanted to show the detail only where relevant, and to hide it when useful.
* Removed sections I felt we could get away with removing, and added detail where relevant. 
* Restructured headings (perhaps it needs more consideration)

There are pros/cons with a lot of the above.

This is by no means the complete solution: I still want to shorten the API section - but I think i have done just enough for you to see where I am going with this.

I hope it is thought provoking and trust you will discard what's useless, and retain what's beneficial (if any can be found).

### CODE REVIEW

**Comment by ddnexus** [comment]
Good progress!

- I like how you added the retypes tools
- I still think "Javascript" should be a topic splitted in subtopics, because the one page version is overwhelmingly long (but maybe it's just because it is still WIP) 
- I would not start from the "Pick a Javascript File" and "Load the Javascript assets" for a few reasons. That may be added as the last thing to do... first ruby and helpers doc, then javascript that supports the helpers (better in a separate page)
- "Overriding *_js helpers? Don't: API is not stable." Not really: the API is stable, but it's more like "you can but you are on your own"... since the javascript file is highly tied with the helper and overwriting may be fragile, so be prepared to maintain your changes on your own.

**Comment by benkoshy** [comment]
In that case I will continue on-wards allowing for the following to be changed:

> * "Overriding *_js helpers? Don't: API is not stable." Not really: the API is stable, but it's more like "you can but you are on your own"... since the javascript file is highly tied with the helper and overwriting may be fragile, so be prepared to maintain your changes on your own.

I will update.

> * I still think "Javascript" should be a topic splitted in subtopics, because the one page version is overwhelmingly long (but maybe it's just because it is still WIP)

I will cut down / simplify as much as possible. I don't have a clear idea on how to split it up - would welcome your thoughts on this one - or even a PR after this one is more polished.

> * I would not start from the "Pick a Javascript File" and "Load the Javascript assets" for a few reasons. That may be added as the last thing to do... first general overview, ruby and helpers doc, then javascript that supports the helpers (better in a separate page)

Agreed.


(Side idea: Also this installation is a little complicated. Perhaps it might be worth a simple Thor generator?)

**Comment by ddnexus** [comment]
> (Side idea: Also this installation is a little complicated. Perhaps it might be worth a simple Thor generator?)

An interacting wizard is nice for the user but a bit involved for you (for what I remember), but it's better than a simple rails template or nothing at all, however... that is low priority. 

Priority should go in this order:

1. Getting the doc content in retype format
2. Improving the content if possible
3. Completing the release (changelog, and other stuff)
4. Release
5. New ideas

We may also put the new ideas into the release but they should not delay it (too much).

**Comment by benkoshy** [comment]
@ddnexus - this is pretty much as much as I can do for this javascript page: http://localhost:5000/pagy/docs/api/javascript/

but it's not complete:  

I don't have clear ideas on how I can split into separate pages / re-order in a cohesive manner.  I would be interested to hear your ideas - would you be opposed handling the following: 

1. Subtopics

> I still think "Javascript" should be a topic splitted in subtopics, because the one page version is overwhelmingly long (but maybe it's just because it is still WIP)

2. Reordering
> would not start from the "Pick a Javascript File" and "Load the Javascript assets" for a few reasons. That may be added as the last thing to do... first general overview, ruby and helpers doc, then javascript that supports the helpers (better in a separate page)

3. Visual explanation via photoshop image - this i can do, because I know photoshop

image

**Comment by ddnexus** [comment]
> I don't have clear ideas on how I can split into separate pages / re-order in a cohesive manner. I would be interested to hear your ideas - would you be opposed handling the following...

Sure, I can do it, besides I think you slashed a bit too much of the previous text, so I will probably resurrect some ghost 👻.

BTW, my idea of splitting still goes like https://github.com/benkoshy/pagy/pull/3#issuecomment-1158617834 ... now adapted to what you added.

**Comment by benkoshy** [comment]
>     Javascript (content of the Overview section, general concepts, links to details, ...
>         Navs
>         Combo Navs
>         Files (Content of js files readme, maybe a better title than "Files") (I can re-order to here) that's easy.
>         AJAX

* Are we gonna have a completely different page extracted from the current one? I don't know what to extract etc or how to do it which is why i suggested a PR to crystalize the vision.

**Comment by ddnexus** [comment]
I mean, just extract the sections in the single page and put them in a separate sub-page(and adding proper page titles and checking the links)... then we can edit the single pages to fit the new organization (if needed).

**Comment by benkoshy** [comment]
Like this:

Javascript 
    Navs (Separate page)
    Combo Navs (Separate page)
    Files (Separate page)
    AJAX (separate page)

If so, this looks easy enough.

**Comment by ddnexus** [comment]
Yes, but the `Javascript` menu should also contain the overview, besides being the root of the sub pages.

**Comment by benkoshy** [comment]
@ddnexus try now. still WIP:

* heading levels to be fixed.
* Images to be added.
* combo and comb-nav sections (I have put them all together) but they can be broken up again into another page.

Hopefully now you can see where this is going and then decide what to do: discard it, keep what's good etc.

**Comment by benkoshy** [comment]
* There are still some quirks. the "tools" category are repeated multiple times.
* Internal links between sub-pages to be added.

**Comment by ddnexus** [comment]
I've pushed a commit to the `dd` branch. It tries to take the good things from old and new, reorganizing the content in just a few pages.

The links of the doc pointing to the old Javascript sections are broken now and should be re-linked. Luckily retype shows them at start.

**Comment by benkoshy** [comment]
Looks good! Feel free to merge/rebase `dd-js` into `benkoshy/retype` branch and let's see the live view: https://benkoshy.github.io/pagy/ in action. Hopefully the github actions should build the webpage and deploy it automatically. 

I can then delete other branches etc, and we can progress on the `retype` branch?

I would only cavil at one single paragraph which I personally think is unnecessarily verbose (i.e. adopting the philosophy of William Zissner in his book - _On Writing Well_ - i wrote  a blog post about it [here](https://benkoshy.github.io/2020/11/11/on-writing-well.html).

**Comment by ddnexus** [comment]
> I would only cavil at one single paragraph which I personally think is unnecessarily verbose
> and... "Zinsser says: write for yourself."

Bad suggestion: that's the very reason it's verbose!!! 🤓

BTW, feel free to propose improvements. As you saw, I added or mixed a lot of your changes that make it better.
You can merge the branch... and delete every branch you want.

The Javascript > pagy_items_selector_js is still incomplete.

In my latest "WIP" commit I added quite a few code-blocks and more are missing.

I will not have time for a few days, so if you want to take over with that, please, take a look at the changes I did for the code bloks. They improve the view, but I am not sure they could improve every page, so add them where you feel it helps, or to be consistent with another page of the same type.

 Then there are the serchkick and meilisearch pages to make consistent with the elasticsearch (that is already modified).

Thanks

**Comment by benkoshy** [comment]
Here it is: https://benkoshy.github.io/pagy/docs/api/javascript/

**Pull request closed without merging**
