### PR TITLE
Fix meilisearch docs

### PR DESCRIPTION
**Pull request by benkoshy**
@ddnexus 

* Commits are atomic and categorized as 'mechanic' (little to no opinion involved), 'snip' - which involves shortening, and highly 'opinionated' commits, so you should be able to follow along/track/revert easily.
* I still want to eliminate a lot of the prose below:

image

Please do not hesitate to ask me to correct problems.

### CODE REVIEW

**Comment by ddnexus** [comment]
The "too many words" problem doesn't exist if you start from elasticsearch_rails and replace what's there with he meilisearch specifics.

It looks like you are going the other way around: modifying the meilisearch docs to make it look good.

**Comment by benkoshy** [comment]
* I made a mistake of comparing to an old version of elasticsearch-rails, hence the confusion.
* Most of the changes were cosmetic, apart from the opinionated changes to comply with `elasticsearch-rails.md`.
* If you're happy to merge, then we have a perfect meeting of the minds with respect to cosmetic changes. 
* The collapsible panels are aesthetically pleasing, and are an improvement. However: they hide the clutter - if you will permit me 🙏🙏🙏🙏🙏, I would very much like to ✂️✂️✂️ to make it even shorter, and sweeter: so users can see it and instantly understand it without thinking at all

**Comment by ddnexus** [comment]
First, let's change all the methods in all pages, by wrapping what is already there with a collapsed panel. Then we can think about cutting the text.

Also, there are other tasks that are incomplete. Like the code blocks of the synopsis (e.g. pagy initializer) etc. If you are adding more changes without finishing the ones that are already half done, then we are adding complexity to our work.

We should probably proceed horizontally to get the same type of changes to the whole documentation, instead of finishing some page at production level, while others don't even have the basic changes. We could do what we want, but I think we should avoid complicating our own efforts.

**Comment by benkoshy** [comment]
> First, let's change all the methods in all pages, by wrapping what is already there with a collapsed panel. Then we can think about cutting the text.

I can do this - no issues. the only reason i am suggesting otherwise is that I can do both (stylistic changes) and cutting at the same time, relatively efficiently - except in separate commits. whether in this branch or another.

In light of the above, please confirm which way you would want me to proceed?

> Also, there are other tasks that are incomplete. Like the code blocks of the synopsis (e.g. pagy initializer) etc. If you are adding more changes without finishing the ones that are already half done, then we are adding complexity to our work.

Sorry I missed that one. if you could mark up in the code review, then I can swiftly correct.

> We should probably proceed horizontally to get the same type of changes to the whole documentation, instead of finishing some page at production level, while others don't even have the basic changes. We could do what we want, but I think we should avoid complicating our own efforts.

> To explain the concept simply: I think we should solve one small thing at the time, completely through the whole doc (and possibly starting from the one that are half implemented), then pass to the second thing, and so on.

Ok - sounds like we should first do all the stylistic changes quickly, and then focus on the more complex ones?

If any problems with the above pls LMK so it can be merged, and we can proceed to knock this over.

**Comment by ddnexus** [comment]
I mean: whatever new style we introduce, we should apply it consistently to all the places it applies, before proceeding with another change. And very firstly, we should complete the changes that are not applied everywhere.

**Pull request closed without merging**
